name: Generate Snake

on:
  schedule: # Run workflow every 6 hours
    - cron: "0 */6 * * *"
  push:
    branches:
    - master  # Default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Output path for the SVG animation
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Upload the generated SVG
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg

      # Commit and push the generated SVG back to the repository
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'yomikkey'
          git config --global user.email 'anukulmickey9@gmail.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
